name       : heimdall
version    : 1.4.2
release    : 2
source     :
    - https://github.com/Benjamin-Dobell/Heimdall/archive/v1.4.2.tar.gz : 589bef88f2597c8a84fe6fafbe928ddc9687438b5b54edd917d7df48c7e3eff8
license    : MIT
component  : system.utils
summary    : Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices.
description: |
    Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libusb-1.0)
    - pkgconfig(Qt5Core)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -D -m 0755 bin/heimdall $installdir/usr/bin/heimdall
    install -D -m 0755 bin/heimdall-frontend $installdir/usr/bin/heimdall-frontend
    install -D -m 0644 heimdall/60-heimdall.rules $installdir%libdir%/udev/rules.d/60-heimdall.rules
    install -D -m 0644 $pkgfiles/heimdall.desktop $installdir/usr/share/applications/heimdall.desktop

