name       : heimdall
version    : 1.4.1
release    : 1
source     :
    - https://github.com/Benjamin-Dobell/Heimdall/archive/v1.4.1.tar.gz : f0a6e4b5bf806fe4ab5413dd869817b600bcd339b642ff46ec0c5fe69adf7230
license    : MIT
component  : system.utils
summary    : Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices.
description: |
    Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(QtCore)
setup      : |
    pushd libpit
    %configure
    popd
    pushd heimdall
    %configure
    popd
    pushd heimdall-frontend
    qmake-qt4 QMAKE_CFLAGS_RELEASE="%CFLAGS%" \
              QMAKE_CXXFLAGS_RELEASE="%CXXFLAGS%" \
              QMAKE_LFLAGS="%LDFLAGS%" \
              QMAKE_MOC=moc-qt4 \
              QMAKE_RCC=rcc-qt4 \
              QMAKE_UIC=uic-qt4 \
              OUTPUTDIR=/usr/bin
build      : |
    for p in libpit heimdall heimdall-frontend; do
        pushd $p
        %make
        popd
    done
install    : |
    pushd heimdall
    %make_install
    popd
    pushd heimdall-frontend
    %make_install INSTALL_ROOT=$installdir